# Generated by Django 5.2.1 on 2025-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_parkingsession_status_parkingslot_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
