# Generated by Django 5.2.1 on 2025-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_alter_parkingsession_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
