# Generated by Django 5.2.1 on 2025-06-17 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0010_auto_20250617_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
