# Generated by Django 5.2.1 on 2025-07-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_userprofile_approval_status_userprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
