# Generated by Django 5.2.1 on 2025-08-01 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_update_admin_users_to_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='Vehicle plate/registration number', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('suv', 'SUV'), ('other', 'Other')], default='car', max_length=20)),
                ('make', models.CharField(blank=True, help_text='e.g., Toyota, Honda', max_length=50, null=True)),
                ('model', models.CharField(blank=True, help_text='e.g., Camry, Civic', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Manufacturing year', null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vehicle is actively used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
