# Generated by Django 5.2.1 on 2025-11-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_arrival', models.DateTimeField(help_text='When customer plans to arrive')),
                ('expected_duration', models.IntegerField(help_text='Expected duration in minutes')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('active', 'Currently Parked'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests', null=True)),
                ('estimated_fee', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('parking_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='pms.parkingsession')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pms.parkingslot')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pms.vehicle')),
            ],
            options={
                'ordering': ['-scheduled_arrival'],
                'indexes': [models.Index(fields=['customer', 'status'], name='pms_booking_custome_139bbc_idx'), models.Index(fields=['scheduled_arrival'], name='pms_booking_schedul_d2ca1f_idx'), models.Index(fields=['status'], name='pms_booking_status_30ba23_idx')],
            },
        ),
    ]
