# Generated by Django 5.2.1 on 2025-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
