# Generated by Django 5.2.1 on 2025-12-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_parkingsession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='camera_detected',
            field=models.BooleanField(default=False, help_text='Camera has detected vehicle in slot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='camera_detected_at',
            field=models.DateTimeField(blank=True, help_text='When camera first detected vehicle', null=True),
        ),
    ]
