# Generated by Django 5.2.1 on 2025-06-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='updated_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='status',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_id',
            field=models.CharField(max_length=20),
        ),
    ]
