# Generated by Django 5.2.1 on 2025-06-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_updated_at_parkingslot_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingSlot',
        ),
    ]
