# Generated by Django 5.2.1 on 2025-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_parkingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
