# Generated by Django 5.2.1 on 2025-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_parkingsession_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
