# Generated by Django 5.2.1 on 2025-06-17 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_parkingsession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
