# Generated by Django 5.2.1 on 2025-06-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_alter_parkingsession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
